IDENTIFIER_TYPE_SYSTEM = "https://hl7.org/fhir/valueset-identifier-type.html"
IDENTIFIER_TYPE_ACCESSION_ID_CODE = "ACSN"
IDENTIFIER_TYPE_SOCIAL_BENEFICIARY_ID_CODE = "SB"
IDENTIFIER_TYPE_PASSPORT_NUMBER_CODE = "PPN"

MARIAL_STATUS_SYSTEM = "https://www.hl7.org/fhir/STU3/valueset-marital-status.html"
MARIAL_STATUS_MARRIED = "M"
MARIAL_STATUS_NEVER_MARRIED = "S"
MARIAL_STATUS_DIVORCED = "D"
MARIAL_STATUS_WIDOWED = "W"
MARIAL_STATUS_UNKNOWN = "U"

ISO_DATE_FORMAT = "%Y-%m-%d"
ISO_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S"
